### ISSUE TITLE
Need documentation!

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/AutoDuolingo#1]
Just need documentation for the four main methods.

**Comment by Kalaborative** [comment]
- [ ] `Type_the_trans()`
- [ ] `mark_Cor_trans()`
- [ ] `type_what_heard()`
- [ ] `select_missing()`

**Comment by Kalaborative** [comment]
See the code in `auto1.py` for reference

**Comment by gmejia-rh** [comment]
I will take this!

**Comment by Kalaborative** [comment]
@madgab thanks!!
