### ISSUE TITLE
Add language support to Readme.md

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/AutoDuolingo#2]
:pen: Simply need a line that describes language functionality.

See if you can figure it out! :smile: Hint: check `auto1.py`

**Comment by bashhike** [comment]
I'd like to take this.

**Comment by bashhike** [comment]
Any comments or shall I open a pull request? @Kalaborative

**Comment by Kalaborative** [comment]
Looks good! Just be sure to include the specific languages... it doesn't currently support all languages on Duolingo yet, only Spanish, French, German, and Italian (I believe...) 
Thanks!

**Comment by Kalaborative** [comment]
Sorry, closing this as this has been resolved by a recent pull request
