### ISSUE TITLE
Error Autodetecting Language

### ISSUE THREAD

**Issue by david-vendel** [Kalaborative/AutoDuolingo#5]
Hello, I decided to try your program as I just build similar myself, and it gives error:

`Autodetecting language...
Traceback (most recent call last):
  File "auto1.py", line 319, in <module>
    raise e
  File "auto1.py", line 314, in <module>
    detect_my_language()
  File "auto1.py", line 85, in detect_my_language
    print( "The program detected you are learning %s. Is this correct?" % tgl)
UnboundLocalError: local variable 'tgl' referenced before assignment`

**Comment by Kalaborative** [comment]
Hi,

It is detecting language too fast. For a quick fix, just insert a `sleep()` call. I will update the main program to include a WebDriverWait so this doesn't occur :smiley:

**Comment by Kalaborative** [comment]
This has been fixed, updated with a WebDriverWait so that this is dynamic.
